### ISSUE TITLE
dlib Installation

### ISSUE THREAD

**Issue by properpan** [therohanrathee/FaceRecon#1]
I ran the code and got the Error of missing libraries. Then I looked the readme and tried to install the required libraries but I think I am unable to install the "**dlib**". I had pasted the whole of terminal output.
Looking forward for assistance.

**Terminal Output**

```
PS C:\Users\pan> pip install opencv-python dlib numpy
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: opencv-python in c:\users\rohan\appdata\roaming\python\python312\site-packages (4.8.1.78)
Collecting dlib
  Using cached dlib-19.24.2.tar.gz (11.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\users\pan\appdata\roaming\python\python312\site-packages (1.26.1)
Building wheels for collected packages: dlib
  Building wheel for dlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for dlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      <string>:208: SyntaxWarning: invalid escape sequence '\('
      <string>:209: SyntaxWarning: invalid escape sequence '\('
      <string>:210: SyntaxWarning: invalid escape sequence '\('
      running bdist_wheel
      running build
      running build_ext
      <string>:125: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      Building extension for Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
      Invoking CMake setup: 'cmake C:\Users\pan\AppData\Local\Temp\pip-install-z1g_5lzf\dlib_c22c27c8d43c4e89888e197ab2aeaa16\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\rohan\AppData\Local\Temp\pip-install-z1g_5lzf\dlib_c22c27c8d43c4e89888e197ab2aeaa16\build\lib.win-amd64-cpython-312 -DPYTHON_EXECUTABLE=C:\Program Files\Python312\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\pan\AppData\Local\Temp\pip-install-z1g_5lzf\dlib_c22c27c8d43c4e89888e197ab2aeaa16\build\lib.win-amd64-cpython-312 -A x64'
      -- Building for: Visual Studio 17 2022
      -- The C compiler identification is unknown
      -- The CXX compiler identification is unknown
      CMake Error at CMakeLists.txt:14 (project):
        No CMAKE_C_COMPILER could be found.



      CMake Error at CMakeLists.txt:14 (project):
        No CMAKE_CXX_COMPILER could be found.



      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 218, in <module>
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\pan\AppData\Local\Temp\pip-build-env-akx6_gdz\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 130, in run
        File "<string>", line 167, in build_extension
        File "C:\Program Files\Python312\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\pan\\AppData\\Local\\Temp\\pip-install-z1g_5lzf\\dlib_c22c27c8d43c4e89888e197ab2aeaa16\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\pan\\AppData\\Local\\Temp\\pip-install-z1g_5lzf\\dlib_c22c27c8d43c4e89888e197ab2aeaa16\\build\\lib.win-amd64-cpython-312', '-DPYTHON_EXECUTABLE=C:\\Program Files\\Python312\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\pan\\AppData\\Local\\Temp\\pip-install-z1g_5lzf\\dlib_c22c27c8d43c4e89888e197ab2aeaa16\\build\\lib.win-amd64-cpython-312', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects
PS C:\Users\pan>
```

**Comment by therohanrathee** [comment]
I think you have not installed [Visual Studio](https://visualstudio.microsoft.com/vs/community/) on your PC.
You have to Download the C++  Development Package.

![image](https://github.com/therohanrathee/FaceRecon/assets/69294451/43da72c2-b45e-425d-982a-deefddaa95d9)


dlib is a C++ library, so to use it you need to have C++ compiler installed, which is CMake in this case.
